### ISSUE TITLE
label include D50\D01\D44

### ISSUE THREAD

**Issue by gengyanlei** [mahdi65/roadDamageDetection2020#4]
xml标签包含D44这样的标签，请问你清楚这是什么原因呢
{'D50': 3581, 'D01': 179, 'D0w0': 1, 'D44': 5057, 'D43': 793, 'D11': 45}

**Comment by sadransh** [comment]
yes the original dataset has those classes but since those ones are rare in cross country dataset So they are not used in this work and challange
