### ISSUE TITLE
TypeError: __init__() missing 2 required positional arguments: 'model' and 'optimizer'

### ISSUE THREAD

**Issue by GMN23362** [mahdi65/roadDamageDetection2020#6]
Does anybody know the answer? I'll be so appreciated if someone could provide help.
![image](https://user-images.githubusercontent.com/74642115/158374652-0d9c2f74-c275-4a75-91d4-03c96c2f58db.png)

**Comment by sadransh** [comment]
The error is because of changes in recent versions of timm library. If you just do `pip install timm==0.1.28` the problem will be resolved
