### ISSUE TITLE
Where is the test directory？

### ISSUE THREAD

**Issue by GMN23362** [mahdi65/roadDamageDetection2020#7]
Some images are neither in train directory nor in val directory. Are they in test directory?
![image](https://user-images.githubusercontent.com/74642115/159118439-9813b5a7-95c0-4e10-a372-ca48fe33ee39.png)
And there is an error like↓, but there is no 'test1' directory.
![image](https://user-images.githubusercontent.com/74642115/159118531-40413385-43bc-4f2e-8bb9-58e2a671c8cf.png)
Thanks for your answer!

**Comment by sadransh** [comment]
Thanks for your interest and pointing out this issue! 
The readme is updated with test data links. find it in section [Usage](https://github.com/mahdi65/roadDamageDetection2020#usage) in 2.
