### ISSUE TITLE
Is there anything wrong with the d1 checkpoint?

### ISSUE THREAD

**Issue by GMN23362** [mahdi65/roadDamageDetection2020#8]
When I opened the link of D1 checkpoint, I found the file's name is 'd0aug_.pth.tar'.
![image](https://user-images.githubusercontent.com/74642115/159158330-bfd16486-11e3-4224-929f-3966ceba7089.png)
By the way, what about the performance and checkpoint of D4_AUG~D7？
Thanks for your answer.

**Comment by sadransh** [comment]
Sorry i don't have acces to our checkpoints backup, as soon as I get access I will update you.

All our test reports exist in the paper. If some specific test does not exist there, it means we did not train, as our access to gpu was limited

**Comment by sadransh** [comment]
Thanks for mentioning this, the link to that checkpoint was incorrect. Just updated the link. 

About your other question, theoretically, the precision for those (not-performed) experiments is somewhere between smaller models and larger models. 

At the time we trained model D7 we had only access to 32GB GPUs for a limited time, so probably if they are trained for longer on 40GB cards; it will reach slightly better F1/mAPs.

**Comment by sadransh** [comment]
@GMN23362 Does it address your issue?
